version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  minio-data:
    driver: local
  airflow-db-volume:
    driver: local
  airflow-logs-volume:
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./shared-workspace:/opt/workspace
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_DEFAULT_BUCKET=test-bucket
      - MAIN_PATH=/opt/workspace
  jupyter-spark-master:
    image: jupyter-spark-master
    container_name: jupyter-spark-master
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - minio
  jupyter-spark-worker-1:
    image: jupyter-spark-worker
    container_name: jupyter-spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8081:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - jupyter-spark-master
      - minio
  jupyter-spark-worker-2:
    image: jupyter-spark-worker
    container_name: jupyter-spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8082:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - jupyter-spark-master
      - minio
  postgres:
    image: postgres:latest
    container_name: postgres2
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    volumes:
      - "./shared-workspace/sql:/docker-entrypoint-initdb.d"
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./shared-workspace:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  airflow-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: ./airflow-image
    depends_on:
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
      MAIN_PATH: /opt/airflow
      S3_BUCKET: dixy-fileshare
    volumes:
      - ./shared-workspace/dags:/opt/airflow/dags
      - ./shared-workspace/logs:/opt/airflow/logs
      - ./shared-workspace/plugins:/opt/airflow/plugins
      - ./shared-workspace/_modules:/opt/airflow/_modules
    ports:
      - "8085:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: ./airflow-image
    depends_on:
      - airflow-webserver
      - airflow-postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      MAIN_PATH: /opt/airflow
      S3_BUCKET: dixy-fileshare
    volumes:
      - ./shared-workspace/dags:/opt/airflow/dags
      - ./shared-workspace/logs:/opt/airflow/logs
      - ./shared-workspace/plugins:/opt/airflow/plugins
      - ./shared-workspace/_modules:/opt/airflow/_modules
    command: scheduler
