FROM apache/airflow:2.7.3-python3.9

USER root

# Установка системных зависимостей (если нужны)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install OpenJDK-11 - нужно для работы спарка
RUN apt update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

USER airflow

# Обновляем pip и setuptools
RUN pip install --upgrade pip setuptools --disable-pip-version-check

# Копируем файл с зависимостями внутрь контейнера
COPY requirements.txt /requirements.txt

# Устанавливаем Python-библиотеки из requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Настраиваем папки для импортов в airflow
ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow/_modules"